name: Deploy Plemiona Bot Frontend to Raspberry Pi

on:
  push:
    branches:
      - main
  workflow_dispatch: # Pozwala na ręczne uruchomienie

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Generate .env file
        run: |
          echo "FRONTEND_IMAGE=${{ vars.FRONTEND_IMAGE }}" >> .env
          echo "VITE_PORT=${{ vars.VITE_PORT }}" >> .env
          echo "VITE_CLERK_PUBLISHABLE_KEY=${{ secrets.VITE_CLERK_PUBLISHABLE_KEY }}" >> .env
          echo "VITE_BACKEND_PLEMIONA=${{ vars.VITE_BACKEND_PLEMIONA }}" >> .env

      - name: Show generated .env (without secrets)
        run: |
          echo "Generated .env file:"
          grep -v "VITE_CLERK_PUBLISHABLE_KEY" .env || true

      - name: Docker Compose
        run: |
          docker compose down
          docker compose pull
          docker compose up -d --build
